### ISSUE TITLE
EPU can indicate image shift group in file names

### ISSUE THREAD

**Issue by Guillawme** [DustinMorado/EPU_group_AFIS#1]
Hi,

This is very helpful, thank you! I especially like the visualization of image shift groups.

But it seems a bit crazy that one has to do all this to figure out which movies belong to which image shift group. Surely, EPU must be able to indicate the image shift group in filenames? It would then be easy to match files belonging to only one group during import in RELION, to import each group independently. So, I tried to find whether the image shift group information is already present in the file name, and according to [CryoSPARC's documentation](https://cryosparc.com/docs/tutorials/ctf-refinement#exposure-groups) this is indeed the case: the first number after `Data` in the file name supposedly encodes image shift group. I checked in a bunch of movies I have that were recorded with EPU, and this first number after `Data` indeed only ever takes 4 different values across all my movies, so this is consistent with an image shift group (although not obvious at all, since these numbers look completely arbitrary and are big).

I am not sure this is done by default, maybe it was set this way in the EPU session that produced this particular set of movies I have? But I would suggest you check what your EPU does, because it seems you can maybe make your life a lot easier to assign image shift groups.

**Comment by DustinMorado** [comment]
Hi,

Thanks for pointing this out to me, I didn't know this beforehand. However unfortunately this only works for splitting up 'exposure groups' into the shots per hole (which is too small of a beam shift for us to really even care about really). It does not make unique values for different holes collected with beam-image shift.

I checked with the most recent AFIS data I collected and printed the two numbers after Data (both seem to be tied to the template) with `sort -n -k3,3 test.txt | uniq` :

```
18135022 18135024 1
18135107 18135109 1
18135022 18135024 2
18135107 18135109 2
18135022 18135024 3
18135107 18135109 3
18135022 18135024 4
18135107 18135109 4
18135022 18135024 5
18135107 18135109 5
18135022 18135024 6
18135107 18135109 6
18135022 18135024 7
18135107 18135109 7
18135022 18135024 8
18135107 18135109 8
18135022 18135024 9
18135107 18135109 9
18135022 18135024 10
18135107 18135109 10
18135022 18135024 11
18135107 18135109 11
18135022 18135024 12
18135107 18135109 12
18135022 18135024 13
18135107 18135109 13
18135022 18135024 14
18135107 18135109 14
18135022 18135024 15
18135107 18135109 15
18135022 18135024 16
18135107 18135109 16
18135022 18135024 17
18135107 18135109 17
18135022 18135024 18
18135107 18135109 18
18135022 18135024 19
18135107 18135109 19
18135022 18135024 20
18135107 18135109 20
18135022 18135024 21
18135107 18135109 21
```

You can see that the values do not correspond with the optics groups and that they just repeat with the two shots per hole I had setup in my template.

We are in conversation with some people at TFS who work on EPU to make sure in the future that it is less tedious to group the data, and included in either the name or the metadata, but currently I am not aware of a better alternative than the one I have posted.

Would you mind if I add this conversation to our forum for those who may be interested in the discussion?

**Comment by Guillawme** [comment]
> Would you mind if I add this conversation to our forum for those who may be interested in the discussion?

Please feel free to do it. 👍 

And I am glad I posted this, because I didn't realize until I read your answer that beam shift is used not only to record several fields of view per hole, but also several holes per stage position (with much larger beam shifts, obviously). I guess I first read the notebook file too fast, because this is actually explained in it already.

You can close this issue, it was only meant as a discussion not as a bug report (maybe I should sign up on the SciLifeLab forum). Maybe see you around the microscope when the pandemic slows down (I am part of the Uppsala BAG).

**Comment by DustinMorado** [comment]
Great, yes thank you very much for your comments. 

You can find the forum [here](http://forum.cryoem.se)

Yes hope to see you around the facility when things return to a semblance of normal.
